# config.py — single source of truth for all Python pipeline config values.
# Every value is documented. Never inline these values elsewhere (STANDARDS.md §2.4).
import os
import sys

WALK_DURATION_SECONDS: int = 8  # Default approach-float time between obstacles
MAX_EPISODE_DURATION_SECONDS: int = 90  # Hard cap on total episode playback time
MIN_OBSTACLE_ACTS: int = 2  # Minimum number of obstacle acts per episode
MAX_OBSTACLE_ACTS: int = 2  # Maximum number of obstacle acts per episode
MIN_CHOICES_PER_ACT: int = 2  # Minimum number of choices presented at each obstacle act
MAX_CHOICES_PER_ACT: int = 2  # Maximum number of choices presented at each obstacle act
MAX_AGENT_RETRY_COUNT: int = 2  # Retries per agent stage on validator failure
POLLING_INTERVAL_SECONDS: int = 3  # Frontend polls status endpoint every N seconds
JOB_TTL_SECONDS: int = 86400  # DynamoDB job record TTL: 24 hours
MAX_SVG_FILE_SIZE_BYTES: int = 512_000  # 500 KB per SVG clip
MAX_EPISODE_JSON_SIZE_BYTES: int = 5_242_880  # 5 MB per episode JSON
MAX_INPUT_TOKENS_PER_STAGE: int = 8_000  # Max tokens sent to a model per agent stage
MAX_OUTPUT_TOKENS_DIRECTOR_STAGE: int = 4_000  # Max tokens generated by the Director stage
MAX_OUTPUT_TOKENS_ANIMATOR_STAGE: int = 12_000  # Max tokens generated by the Animator stage
MAX_OUTPUT_TOKENS_DRAWING_STAGE: int = 12_000  # Max tokens generated by the Drawing stage
MAX_OUTPUT_TOKENS_RENDERER_STAGE: int = 12_000  # Max tokens generated by the Renderer stage
MAX_PARALLEL_DRAWING_TASKS: int = 4  # Max concurrent Drawing tasks across obstacles/backgrounds
MAX_PROMPT_LENGTH_CHARS: int = 500  # Max length of user-supplied generation prompt
MAX_TITLE_LENGTH_CHARS: int = 60  # Max episode title length for the studio UI
MAX_DESCRIPTION_LENGTH_CHARS: int = 120  # Max episode description length for the studio UI
MAX_CHOICE_LABEL_LENGTH_CHARS: int = 40  # Max choice button label length for the studio UI
EPISODE_SCHEMA_VERSION: str = "1.0"  # Episode artifact schema version written at generation time
# --- Per-agent Bedrock model IDs ---
# Drawing agent uses Opus for highest SVG quality.
# All other agents use Sonnet for cost efficiency.
# Each agent reads its own env var; warn on fallback per STANDARDS.md §1.

#eu.anthropic.claude-sonnet-4-5-20250929-v1:0
#eu.anthropic.claude-sonnet-4-20250514-v1:0
_BEDROCK_MODEL_ID_DIRECTOR_DEFAULT = "eu.anthropic.claude-sonnet-4-6"
_director_model_from_env = os.getenv("BEDROCK_MODEL_ID_DIRECTOR")
if _director_model_from_env is None:
    print(
        "WARN [config] BEDROCK_MODEL_ID_DIRECTOR not set; "
        f"using default: {_BEDROCK_MODEL_ID_DIRECTOR_DEFAULT}",
        file=sys.stderr,
    )
BEDROCK_MODEL_ID_DIRECTOR: str = _director_model_from_env or _BEDROCK_MODEL_ID_DIRECTOR_DEFAULT

_BEDROCK_MODEL_ID_ANIMATOR_DEFAULT = "eu.anthropic.claude-sonnet-4-6"
_animator_model_from_env = os.getenv("BEDROCK_MODEL_ID_ANIMATOR")
if _animator_model_from_env is None:
    print(
        "WARN [config] BEDROCK_MODEL_ID_ANIMATOR not set; "
        f"using default: {_BEDROCK_MODEL_ID_ANIMATOR_DEFAULT}",
        file=sys.stderr,
    )
BEDROCK_MODEL_ID_ANIMATOR: str = _animator_model_from_env or _BEDROCK_MODEL_ID_ANIMATOR_DEFAULT

_BEDROCK_MODEL_ID_DRAWING_DEFAULT = "eu.anthropic.claude-opus-4-6-v1"
_drawing_model_from_env = os.getenv("BEDROCK_MODEL_ID_DRAWING")
if _drawing_model_from_env is None:
    print(
        "WARN [config] BEDROCK_MODEL_ID_DRAWING not set; "
        f"using default: {_BEDROCK_MODEL_ID_DRAWING_DEFAULT}",
        file=sys.stderr,
    )
BEDROCK_MODEL_ID_DRAWING: str = _drawing_model_from_env or _BEDROCK_MODEL_ID_DRAWING_DEFAULT

_BEDROCK_MODEL_ID_RENDERER_DEFAULT = "eu.anthropic.claude-sonnet-4-6"
_renderer_model_from_env = os.getenv("BEDROCK_MODEL_ID_RENDERER")
if _renderer_model_from_env is None:
    print(
        "WARN [config] BEDROCK_MODEL_ID_RENDERER not set; "
        f"using default: {_BEDROCK_MODEL_ID_RENDERER_DEFAULT}",
        file=sys.stderr,
    )
BEDROCK_MODEL_ID_RENDERER: str = _renderer_model_from_env or _BEDROCK_MODEL_ID_RENDERER_DEFAULT

DRAWING_TEMPERATURE: float = 0.5  # Lower temperature for more consistent SVG output
BEDROCK_CONNECT_TIMEOUT_SECONDS: int = 10  # SDK connect timeout for Bedrock HTTPS requests
AGENT_CALL_TIMEOUT_SECONDS: int = 300  # SDK read timeout for one Bedrock agent/model request
JOB_DEADLINE_SECONDS: int = 480  # Total orchestrator Lambda timeout budget
CANVAS_WIDTH: int = 800  # SVG canvas width in pixels
CANVAS_HEIGHT: int = 200  # SVG canvas height in pixels
GROUND_LINE_Y: int = 160  # Invisible floor coordinate — not rendered as a visible line
SUPPORT_Y_TOLERANCE_PX: int = 5  # Max pixels grounded poses may drift vertically from support_y
ANIMATOR_GROUNDED_CHARACTER_Y_NORMALIZE_TOLERANCE_PX: int = (
    8  # Snap small grounded character_y near-misses onto support_y before validation retries
)
HANDOFF_SUPPORT_Y_TOLERANCE_PX: int = 2  # Max vertical drift for handoff poses from support_y
MIN_CHARACTER_Y_IN_FRAME_PX: int = (
    88  # Keep Linai high enough in-frame that upward beats do not clip the cloud offscreen
)
HANDOFF_CHARACTER_X: int = 160  # Canonical x-position for act-boundary continuation poses
HANDOFF_X_TOLERANCE_PX: int = 5  # Max pixels a handoff pose may drift from HANDOFF_CHARACTER_X
APPROACH_OBSTACLE_CLEARANCE_PX: int = (
    40  # Grounded approach clips must stop at least this far before the obstacle
)
MAX_GROUNDED_APPROACH_CHARACTER_X: int = (
    190  # Grounded approach clips may settle close to the staged obstacle, but not read as past it
)
RETRY_DEADLINE_SAFETY_MARGIN_SECONDS: int = (
    5  # Reserve a small cleanup/logging buffer before attempting another expensive retry
)
MIN_STAGE_START_BUDGET_SECONDS: int = (
    30  # Do not start another heavy orchestration stage when too little Lambda time remains
)
OBSTACLE_EMBED_X: int = 350  # Scene x-position where a 120x150 obstacle SVG is embedded
OBSTACLE_EMBED_Y: int = 18  # Scene y-position where a 120x150 obstacle SVG is embedded
OBSTACLE_EMBED_WIDTH: int = 120  # Rendered obstacle width inside the 800x200 scene
OBSTACLE_EMBED_HEIGHT: int = 150  # Rendered obstacle height inside the 800x200 scene
RENDERER_GROUNDED_TRAVEL_MIN_PX: int = (
    25  # Grounded clips that travel at least this far must show visible stepping
)
RENDERER_ROOT_TRANSLATE_MAX_Y_PX: int = (
    4  # Renderer may only dip Linai slightly downward before she clips below the scene frame
)
RENDERER_EYE_DRIFT_MAX_X_PX: int = (
    3  # Eye interior motion must stay small so pupils/iris do not skate across the socket
)
RENDERER_EYE_DRIFT_MAX_Y_PX: int = (
    2  # Vertical eye drift must stay tighter than horizontal drift for readable eye contact
)
RENDERER_EYE_ROTATE_MAX_DEGREES: int = (
    12  # Eye interior rotation must stay subtle so socket contents do not whip unnaturally
)
RENDERER_BODY_SCALE_MIN: float = (
    0.8  # Linai body squash/stretch must stay gentle enough to preserve her silhouette
)
RENDERER_BODY_SCALE_MAX: float = (
    1.2  # Linai body squash/stretch must stay gentle enough to preserve her silhouette
)
RENDERER_FAIL_ROOT_TRANSLATE_MAX_Y_PX: int = (
    25  # Fail clips may dip Linai further on collision impact (dramatic fall reaction)
)
RENDERER_FAIL_BODY_SCALE_MAX: float = (
    1.5  # Fail clips allow more squash/stretch for a dramatic impact reaction
)

# Progress stage labels — displayed verbatim in the browser progress indicator (GEN-05).
# These strings are the single source of truth: they live here, and both the generate
# Lambda and the orchestrator import them. The frontend only renders what it receives.
STAGE_KB_QUERY: str = "[1/6] Querying character knowledge base..."
STAGE_GENERATE_SCRIPT: str = "[2/6] Generating story script..."
STAGE_VALIDATE_SCRIPT: str = "[3/6] Validating script structure..."
STAGE_ANIMATE_KEYFRAMES: str = "[4/6] Designing animation keyframes..."
STAGE_DRAW_ASSETS: str = "[5/6] Drawing SVG assets..."   # Drawing agent: obstacles + backgrounds
STAGE_RENDER_SVG: str = "[6/6] Rendering SVG clips..."   # Renderer agent: final animation clips
STAGE_FAILED: str = "Generation failed"  # Terminal failure label shown in UI
