// Build-time configuration — regenerated by `npm run build` from env vars.
// Defaults here are safe for local proxy development (proxy routes /episodes/* to CloudFront).
// To bake real values in: set CLOUDFRONT_DOMAIN before running the build.

/** CloudFront distribution origin. Empty string falls back to proxy-relative URLs in dev. */
export const CLOUDFRONT_DOMAIN = "";

/** Local proxy route that serves the public viewer shell against repo-managed episodes. */
export const LOCAL_PREVIEW_BASE_PATH = "/preview";

/** How often the browser polls the status endpoint while a job is running (ms). */
export const POLL_INTERVAL_MS = 3_000;

/** localStorage key used to persist an in-progress job ID across page reloads. */
export const JOB_ID_STORAGE_KEY = "linions.jobId";
